language: python

python:
  - 3.6

services:
  - postgresql

env:
  global:
    - APP_SETTINGS ='testing'

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - "psql -c 'create database ireporter;' -U postgres"

script:
  - py.test --cov=app
  - coverage report

after_success:
 - coveralls